version: '2'
services:
  frpc:
    image: nykma/frp:latest
    restart: always
    volumes:
      - ./config:/frp/config
      - ./log:/frp/log
    extra_hosts:
     #To visit host's port in a container,
     #you should fill in the correct IP of your docker host.
      - "dockerhost:120.78.72.49"
   ports:
      - "127.0.0.1:7400:7400" # admin_port

#  frps:
#    image: nykma/frp:latest
#    network_mode: host
#    restart: always
#    volumes:
#      - ./config:/frp/config
#      - ./log:/frp/log
#    ports:
#      - "7000:7000"     # bind_port
#      - "7000:7000/udp" # kcp_bind_port
#     - "7500:7500"     # dashboard_port
#     - "80:80"   # vhost_http_port
#     - "443:443" # vhost_https_port
#     # WARNING: container up/down will be VERY SLOW (even failed)
#     # if too much ports opened here!
      #- "20000-20020:2000-2020"
    entrypoint:
      - '/frp/frpc'
      - '-c'
      - 'config/frpc.ini'